#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_width          5
yabai -m config active_window_border_color   0xff3388cc
yabai -m config normal_window_border_color   0xff777777
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  6
yabai -m config bottom_padding               6
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   6

# SPACEBAR_HEIGHT=$(spacebar -m config height)
# yabai -m config external_bar all:0:$SPACEBAR_HEIGHT

# rule
# float system preferences
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Simulator$" manage=off

# show digital colour meter topmost and on all spaces
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on


yabai -m rule --add app="^DBeaver" title="^Choose SQL script for" manage=off
yabai -m rule --add app="^DBeaver" title="^Connection .+ configuration$" manage=off
yabai -m rule --add app="^DBeaver" title="^Tip of the day" manage=off
yabai -m rule --add app="^DBeaver" title="^Choose catalog/schema" manage=off
yabai -m rule --add app="^DBeaver" title="Persist Changes" manage=off


yabai -m rule --add app="^Firefox Nightly$" title="^Opening " manage=off
yabai -m rule --add title="^Picture-in-Picture$" sticky=on
yabai -m rule --add title="^Sign in - Google Accounts" manage=off

yabai -m rule --add title="^Tunnelblick" manage=off
yabai -m rule --add title="^CleanShot" manage=off




echo "yabai configuration loaded.."
