#!/usr/bin/env zsh
# FONT="Hack Nerd Font Mono"
# FONT="JetBrainsMono Nerd Font"
FONT="JetBrains Mono NL Nerd Font"
# "SF Pro"

############## BAR ##############
sketchybar -m --bar height=25 \
                    blur_radius=0 \
                    position=bottom \
                    padding_left=5 \
                    padding_right=5 \
                    margin=0 \
                    corner_radius=0 \
                    color=0xff2E3440 \
                    border_width=0 \
                    border_color=0xff2E3440

############## GLOBAL DEFAULTS ##############
sketchybar -m --default updates=when_shown \
                        drawing=on \
    background.color=0x66494d64 \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
                        icon.font="$FONT:Regular:14.0" \
                        icon.color=0xffECEFF4 \
                        icon.highlight_color=0xff9FEE5C \
                        label.font="$FONT:Regular:14.0" \
                        label.color=0xffECEFF4

############## SPACE DEFAULTS ##############
sketchybar -m --default label.padding_left=0 \
                        label.padding_right=0 \
                        icon.padding_left=6 \
                        icon.padding_right=6

sketchybar -m --add item logo left \
              --set logo icon= \
                    background.color=0xffBF616A \
                    background.height=20 \
                    background.padding_right=0 \
                    click_script="sketchybar -m --update"

############## PRIMARY DISPLAY SPACES ##############
sketchybar -m --add space productivity left \
              --set productivity associated_space=1 \
                         associated_display=1 \
			 icon=􀃋 \
                         click_script="yabai -m space --focus 1" \
                         background.color=0xffD8DEE9 \
                         background.drawing=off \
              --subscribe productivity mouse.entered mouse.exited \
                                                                 \
              --add space browser left \
              --set browser associated_display=1 \
                         associated_space=2 \
			 icon=􀃍 \
                         click_script="yabai -m space --focus 2" \
                         background.color=0xffD8DEE9 \
                         background.drawing=off \
              --subscribe browser mouse.entered mouse.exited \
                                                                 \
              --add space messaging left \
              --set messaging associated_display=1 \
                         associated_space=3 \
                         icon= \
                         click_script="yabai -m space --focus 3" \
                         background.color=0xffD8DEE9 \
                         background.drawing=off \
              --subscribe messaging mouse.entered mouse.exited \
                                                                 \
              --add space reference left \
              --set reference associated_display=1 \
                         associated_space=4 \
			 icon=􀃑 \
                         click_script="yabai -m space --focus 4" \
                         background.color=0xffD8DEE9 \
                         background.drawing=off \
              --subscribe reference mouse.entered mouse.exited \
                                                                 \
              --add space code left \
              --set code associated_display=1 \
                         associated_space=5 \
			 icon=􀃓 \
                         click_script="yabai -m space --focus 5" \
                         background.color=0xffD8DEE9 \
                         background.drawing=off \
              --subscribe code mouse.entered mouse.exited \
                                                                 \
              --add space media left \
              --set media associated_display=1 \
                         associated_space=6 \
                         icon=􀃕\
                         click_script="yabai -m space --focus 6" \
                         background.color=0xffD8DEE9 \
                         background.drawing=off \
              --subscribe media mouse.entered mouse.exited \
                                                                 \
              --add space feed left \
              --set feed associated_display=1 \
                         associated_space=7 \
                         icon=􀃗\
                         click_script="yabai -m space --focus 7" \
                         background.color=0xffD8DEE9 \
                         background.drawing=off \
              --subscribe feed mouse.entered mouse.exited \
                                                                 \
              --add space system left \
              --set system associated_display=1 \
                         associated_space=8 \
                         icon=􀃙\
                         click_script="yabai -m space --focus 8" \
                         background.color=0xffD8DEE9 \
                         background.drawing=off \
              --subscribe system mouse.entered mouse.exited \
                                                                 \
              --add space vm left \
              --set vm associated_display=1 \
                         associated_space=9 \
			 label="9" \
                         click_script="yabai -m space --focus 9" \
                         background.color=0xffD8DEE9 \
                         background.drawing=off \
              --subscribe vm mouse.entered mouse.exited

sketchybar -m --add item yabai_logo left \
              --set yabai_logo icon="" \
                               background.color=0xffD08770 \
                               background.height=20 \
                               background.padding_left=5 \
                               icon.font="$FONT:Regular:14.0"

# icons=("􀃉" "􀃋" "􀃍" "􀃏" "􀃑" "􀃓" "􀃕" "􀃗" "􀃙" "􀃛" "􀕒" "􀕓" "􀕔" "􀕕" "􀕖") #0 to 14
# highlight_colors=("" "0xff9dd274" "0xfff69c5e" "0xff72cce8" "0xffeacb64" "0xff9dd274" "0xfff69c5e" "0xff72cce8" "0xffeacb64" "0xff9dd274" "0xfff69c5e" "0xff72cce8" "0xffeacb64" "0xff9dd274" "0xfff69c5e")
#
# args=()
# QUERY="$(yabai -m query --spaces | jq -r '.[] | [.index, .windows[0], .label, .display, .["is-visible"]] | @sh')"
#
# NAMES=""
# while read -r index window yabai_name display visible
# do
#   NAME="$(echo "${yabai_name}" | tr -d "'")"
#   if [ "${window}" = "null" ]; then
#     label="$NAME"
#   else
#     label="$NAME*"
#   fi
#   if [ "$NAME" = "" ] || [ "$NAME" = " " ]; then 
#     NAME="${index}"
#   fi
#   
#   NAMES="$NAMES $NAME"
#   args+=(--clone "$NAME" space_template after \
#          --set "$NAME" label="${label}" \
#                        icon="${icons[${index}]}" \
#                        icon.highlight_color="${highlight_colors[${index}]}" \
#                        associated_display=${display} \
#                        icon.highlight=${visible} \
#                        drawing=on)
# done <<< "$QUERY"
#
# args+=(--reorder $NAMES)
# sketchybar -m ${args[@]} &> /dev/null
